version: '3.8'

services:
 backend:
   build: ./backend
   ports:
    - 3002:3002
   volumes:
    - ./backend:/usr/src/backend
   environment:
    - MONGO_URL=mongodb://mongo:27017/mydatabase
   command: npm run dev
   depends_on:
    - mongo  
 frontend:
    build: ./frontend
    ports:
     - 5173:5173
    volumes:
     - ./frontend:/usr/src/frontend 
    environment:
     - VITE_BACKEND_URL=http://localhost:3002
    depends_on:
     - backend
 mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: